version: '3'
services:

  app:
    build: app
    stdin_open: true
    volumes:
      - ./app:/app

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/pass123
      NEO4J_dbms_logs_debug_level: DEBUG
